import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
df = pd.read_csv("SeoulBikeData.csv",encoding='unicode_escape')
plt.figure(figsize=(8,4))
plt.hist(df["Rented Bike Count"],bins=31,edgecolor="black")
plt.xlabel("Rented Bike count")
plt.ylabel("Frequency")
plt.title("Histogram of rented bike count")
plt.savefig("histogram")

plt.figure(figsize=(8,4))
plt.boxplot(df["Rented Bike Count"],vert=False)
plt.xlabel("Rented Bike count")
plt.title("Box plot of rented bike count")
plt.savefig('boxplot')
plt.show()

plt.figure(figsize=(8,4))
plt.hist(df["Temperature(°C)"],bins=31,edgecolor="black")
plt.xlabel("Temperature(°C)")
plt.ylabel("Frequency")
plt.title("Histogram of Temperature(°C)")
plt.savefig('histogram_temperature')

plt.figure(figsize=(8,4))
plt.hist(df["Wind speed (m/s)"],bins=31,edgecolor="black")
plt.xlabel("Wind speed (m/s)")
plt.ylabel("Frequency")
plt.title("Histogram of Wind speed (m/s)")
plt.savefig('histogram_wind_speed')

plt.figure(figsize=(8,4))
plt.hist(df["Visibility (10m)"],bins=31,edgecolor="black")
plt.xlabel("Visibility (10m)")
plt.ylabel("Frequency")
plt.title("Histogram of Visibility (10m)")
plt.savefig('histogram_visibility')

plt.figure(figsize=(8,4))
plt.hist(df["Dew point temperature(°C)"],bins=31,edgecolor="black")
plt.xlabel("Dew point temperature(°C)")
plt.ylabel("Frequency")
plt.title("Histogram of Dew point temperature(°C)")
plt.savefig('histogram_dew_point_temperature')

plt.figure(figsize=(8,4))
plt.hist(df["Solar Radiation (MJ/m2)"],bins=31,edgecolor="black")
plt.xlabel("Solar Radiation (MJ/m2)")
plt.ylabel("Frequency")
plt.title("Histogram of Solar Radiation (MJ/m2)")
plt.savefig('histogram_solar_radiation')

plt.figure(figsize=(8,4))
plt.hist(df["Rainfall(mm)"],bins=31,edgecolor="black")
plt.xlabel("Rainfall(mm)")
plt.ylabel("Frequency")
plt.title("Histogram of Rainfall(mm)")
plt.savefig('histogram_rainfall')

plt.figure(figsize=(8,4))
plt.hist(df["Snowfall (cm)"],bins=31,edgecolor="black")
plt.xlabel("Snowfall (cm)")
plt.ylabel("Frequency")
plt.title("Histogram of Snowfall (cm)")
plt.savefig('histogram_snowfall')

plt.figure(figsize=(8,4))
plt.hist(df["Humidity(%)"],bins=31,edgecolor="black")
plt.xlabel("Humidity(%)")
plt.ylabel("Frequency")
plt.title("Histogram of Humidity(%)")
plt.savefig('histogram_humidity')

df['square'] = np.sqrt(df['Rented Bike Count'].values)
plt.figure(figsize=(8,4))
plt.hist(df["square"],bins=31,edgecolor="black")
plt.xlabel("Rented Bike count")
plt.ylabel("Frequency")
plt.title("Histogram of rented bike count")
plt.savefig("histogram_root")
